source 'http://github.com/CocoaPods/Specs.git'
source 'https://git.coding.net/pizhulovecode/MyPodsRepo.git'
use_frameworks!

target 'MyFirstPod_Example' do
  pod 'MyFirstPod', :path => '../'

  target 'MyFirstPod_Tests' do
    inherit! :search_paths
    
  end

  pod 'MyFirstPod'
end
